# Generated by Django 6.0.7 on 2026-07-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_question_choice_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(default='online course', max_length=30),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='mode',
            field=models.TextField(choices=[('audit', 'Audit'), ('honor', 'Honor'), ('BETA', 'BETA')], default='audit', max_length=5),
        ),
        migrations.AlterField(
            model_name='learner',
            name='occupation',
            field=models.TextField(choices=[('student', 'Student'), ('developer', 'Developer'), ('data_scientist', 'Data Scientist'), ('dba', 'Database Admin')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(default='title', max_length=200),
        ),
    ]
